import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import  FavoritesProvider  from '@/Context/favoritesContext';

export const metadata = {
  title:
    "Booking.com | Official site | The best hotels, flights, car rentals & accommodations ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body>
      <FavoritesProvider>

        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        </FavoritesProvider>

      </body>
    </html>
  );
}
